### ISSUE TITLE
Make a hierarchy file for the used components.

### ISSUE THREAD

**Issue by JMGama** [JMGama/WhatsApp-Scraping#3]
### Context
Since the Whatsapp Web page is made with React, everytime they re-deploy, the class names changes and all the project fall apart. 💔 

### Requirement
A great idea from **Naveen Prasanth** was to make a file with the hierarchy of the components so we can make calibration and update the class names automatically when the application starts.

### Example:
The left panel that has the chatters has the next hierarchy `html/body/div/div/div/div/div/div/div/div/div/div`

**Comment by VISWESWARAN1998** [comment]
Would like to know more about this project, I would like to contribute.

Regards,
Visweswaran N

**Comment by NaveenPrasanth** [comment]
Hi JMGama! I am Naveen Prasanth. I would like to take this feature to completion. Sorry for the delayed  response.

**Comment by NaveenPrasanth** [comment]
Please confirm if any one is already working on this.

**Comment by JMGama** [comment]
Thanks for the help @NaveenPrasanth go on, no one is working on this feature! Thanks a lot! 💖

**Comment by JMGama** [comment]
Fixed in the latest Merge #5 👍
